// CCP 400 Answers & Explanations: Questions 1 - 100
module.exports = {
  1: { ans: ['A', 'C'], cat: 'Cloud Foundations', exp: 'Migrating to AWS provides operational resilience (high availability, automated disaster recovery) and business agility (rapid innovation and provisioning).' },
  2: { ans: ['B'], cat: 'Cloud Architecture', exp: 'Taking advantage of advanced technologies quickly by democratizing complex infrastructure with managed/serverless services is a core principle of Performance Efficiency.' },
  3: { ans: ['D'], cat: 'Networking', exp: 'Amazon CloudFront is a global Content Delivery Network (CDN) that delivers video content with low latency using worldwide edge locations.' },
  4: { ans: ['B'], cat: 'Cloud Foundations', exp: 'An Availability Zone (AZ) consists of one or more discrete data centers with redundant power, networking, and connectivity in an AWS Region.' },
  5: { ans: ['B'], cat: 'Cloud Architecture', exp: 'The Reliability pillar focuses on recovering from infrastructure disruptions and dynamically allocating resources to meet demand.' },
  6: { ans: ['C'], cat: 'Security & Compliance', exp: 'Configuration management is a shared control: AWS maintains configuration of its infrastructure devices, while the customer configures their guest OS, network, and applications.' },
  7: { ans: ['A', 'D'], cat: 'Compute', exp: 'In AWS Lambda serverless execution, the customer is responsible for writing/updating the application code and securing code logic/dependencies.' },
  8: { ans: ['A'], cat: 'Compute', exp: 'Amazon EC2 Dedicated Hosts provide physical server isolation dedicated exclusively to a single customer workload, essential for compliance and licensing.' },
  9: { ans: ['C'], cat: 'Security & Compliance', exp: 'Under the AWS Shared Responsibility Model, security and compliance are shared duties between AWS (security OF the cloud) and the customer (security IN the cloud).' },
  10: { ans: ['D'], cat: 'Cloud Architecture', exp: 'Implementing elasticity allows applications to dynamically scale compute capacity up or down based on traffic demand.' },
  11: { ans: ['B', 'C'], cat: 'Compute', exp: 'Amazon Machine Images (AMIs) and Amazon EBS snapshots allow creating point-in-time image backups and disk copies to restore EC2 instances in disaster recovery scenarios.' },
  12: { ans: ['B'], cat: 'Billing & Support', exp: 'AWS Cost Explorer lets users view, analyze, and forecast historical usage and spending for AWS services like EC2 and RDS over the past 12+ months.' },
  13: { ans: ['B'], cat: 'Billing & Support', exp: 'The AWS Concierge Support team is a senior customer service partner assigned exclusively to Enterprise Support plan customers for billing and account management.' },
  14: { ans: ['C'], cat: 'Billing & Support', exp: 'AWS Organizations consolidated billing enables linking multiple AWS department accounts to a single master management account with one unified monthly bill.' },
  15: { ans: ['C'], cat: 'Cloud Architecture', exp: 'Distributing workloads across multiple Availability Zones adheres to the "Design for failure" principle by ensuring redundant operation if one AZ fails.' },
  16: { ans: ['B'], cat: 'Security & Compliance', exp: 'AWS is strictly responsible for the physical security, facilities, and underlying hardware across its global infrastructure.' },
  17: { ans: ['B'], cat: 'Compute', exp: 'AWS Lambda is an event-driven, serverless compute service that executes code in response to data/state changes with zero idle compute cost.' },
  18: { ans: ['D'], cat: 'DevOps & Automation', exp: 'AWS SDKs (Software Development Kits) provide programming language APIs to interact with and manage AWS services programmatically.' },
  19: { ans: ['B'], cat: 'Security & IAM', exp: 'Customers are solely responsible for managing, rotating, and securing their IAM user credentials and secret access keys.' },
  20: { ans: ['D'], cat: 'Security & Compliance', exp: 'To run a PCI-compliant workload, customers must choose AWS services that are in-scope for PCI DSS and configure their application-level PCI security controls.' },
  21: { ans: ['A', 'D'], cat: 'Cost & Optimization', exp: 'AWS Trusted Advisor inspects environments across 5 pillars: Cost Optimization, Performance, Security, Fault Tolerance, and Service Quotas.' },
  22: { ans: ['A'], cat: 'Storage', exp: 'Selecting the appropriate S3 storage tier (e.g., S3 Standard, S3 Infrequent Access, S3 Glacier) has the largest impact on long-term data lake storage costs.' },
  23: { ans: ['B'], cat: 'Cost & Optimization', exp: 'Savings Plans (or 1-year Standard Reserved Instances) offer significant cost savings (up to 72%) for continuous, steady-state compute workloads.' },
  24: { ans: ['B'], cat: 'Cloud Architecture', exp: 'Performing operations as code (Infrastructure as Code) is a cornerstone design principle of the Operational Excellence pillar.' },
  25: { ans: ['C'], cat: 'Security & Compliance', exp: 'When using Amazon RDS managed database service, customers configure network access rules and firewall filtering using Security Groups.' },
  26: { ans: ['C'], cat: 'Security & Compliance', exp: 'For any AWS managed service, the customer always retains ownership and responsibility for customer data encryption and data protection.' },
  27: { ans: ['A'], cat: 'Billing & Support', exp: 'Cost allocation tags enable businesses to label and categorize AWS resources to allocate spending by department, cost center, or project.' },
  28: { ans: ['B'], cat: 'Billing & Support', exp: 'Service Quotas allows users to centrally view and request quota (limit) increases across all AWS services from one console.' },
  29: { ans: ['B'], cat: 'Cloud Architecture', exp: 'The Operational Excellence pillar focuses on running systems, continual improvement, and learning from operational failures.' },
  30: { ans: ['B'], cat: 'Security & Monitoring', exp: 'AWS CloudTrail captures and records API calls, identifying the IAM user, IP address, and timestamp for all account events.' },
  31: { ans: ['A'], cat: 'Billing & Support', exp: 'All AWS accounts have access to core AWS Trusted Advisor checks (such as S3 bucket permissions, IAM root MFA, and specific service limits).' },
  32: { ans: ['C'], cat: 'Security & Compliance', exp: 'Firewall configuration (Security Groups and Network ACLs) is an example of Security IN the Cloud managed directly by the customer.' },
  33: { ans: ['A'], cat: 'Security & Compliance', exp: 'AWS Artifact is the central portal for on-demand access to AWS compliance reports, SOC/PCI certifications, and security agreements.' },
  34: { ans: ['B'], cat: 'Security & IAM', exp: 'Changing or cancelling the AWS Support plan requires signing in with the root user credentials of the AWS account.' },
  35: { ans: ['C'], cat: 'Security & IAM', exp: 'Service Control Policies (SCPs) define and enforce maximum permission boundaries across member accounts in AWS Organizations.' },
  36: { ans: ['A'], cat: 'Security & Monitoring', exp: 'AWS Config continually monitors, evaluates, and audits configuration changes and compliance history of AWS resources.' },
  37: { ans: ['B'], cat: 'Cloud Architecture', exp: 'Deploying web servers across multiple AWS Regions enhances high availability and disaster resilience against regional disruptions.' },
  38: { ans: ['B'], cat: 'Security & Compliance', exp: 'Patch management is a shared control: AWS patches host hardware and managed services, while customers patch EC2 guest operating systems.' },
  39: { ans: ['D'], cat: 'Networking', exp: 'An Amazon Virtual Private Cloud (VPC) spans all Availability Zones within a single designated AWS Region.' },
  40: { ans: ['B', 'D'], cat: 'Networking', exp: 'An AWS Site-to-Site VPN connects an on-premises network via a Customer Gateway to an AWS Virtual Private Gateway (or Transit Gateway).' },
  41: { ans: ['A'], cat: 'Security & IAM', exp: 'Applying Least Privilege means granting users only the minimum necessary permissions required to execute their specific job tasks.' },
  42: { ans: ['B'], cat: 'Cloud Architecture', exp: 'Decoupling components into loosely coupled microservices prevents cascading system failures and allows independent scaling.' },
  43: { ans: ['B'], cat: 'Cloud Architecture', exp: 'A system that automatically scales capacity in response to real-time workload fluctuations demonstrates cloud elasticity.' },
  44: { ans: ['A'], cat: 'Cloud Architecture', exp: 'Running an application across multiple Availability Zones provides high availability with automatic failover and redundancy.' },
  45: { ans: ['B'], cat: 'Networking', exp: 'VPC peering establishes a direct network route between two VPCs (even across AWS Regions) using private IP addressing.' },
  46: { ans: ['A'], cat: 'Databases', exp: 'With Amazon RDS, the customer manages database user credentials, connections, queries, and data schemas.' },
  47: { ans: ['A'], cat: 'Compute', exp: 'When using AWS Lambda, customers are responsible for managing function versions, aliases, code packages, and IAM execution roles.' },
  48: { ans: ['A', 'D'], cat: 'Security & Compliance', exp: 'Decommissioning physical disks and physical access control to data centers are strict responsibilities of AWS, not the customer.' },
  49: { ans: ['C'], cat: 'Billing & Support', exp: 'AWS Enterprise Support provides a dedicated Concierge team for white-glove billing assistance and account operational support.' },
  50: { ans: ['A', 'D'], cat: 'Cost & Optimization', exp: 'AWS Trusted Advisor provides real-time guidance across Cost Optimization, Security, Fault Tolerance, Performance, and Service Quotas.' },
  51: { ans: ['D'], cat: 'Compute', exp: 'Amazon EC2 Auto Scaling automatically adds or terminates EC2 instances according to demand conditions and scaling policies.' },
  52: { ans: ['D'], cat: 'Security & Networking', exp: 'A Security Group functions as a virtual stateful firewall controlling inbound and outbound traffic at the EC2 instance level.' },
  53: { ans: ['C'], cat: 'Security & Compliance', exp: 'Customer-managed encryption (e.g. KMS customer-managed keys) provides customer control over data encryption options.' },
  54: { ans: ['B'], cat: 'Billing & Support', exp: 'Enterprise Support includes a designated Technical Account Manager (TAM) who provides proactive technical guidance and architecture reviews.' },
  55: { ans: ['D'], cat: 'Cloud Foundations', exp: 'Elasticity allows an infrastructure to automatically adjust compute capacity to maintain steady performance as load fluctuates.' },
  56: { ans: ['A', 'C', 'D'], cat: 'Cost & Optimization', exp: 'In AWS cloud TCO, primary recurring operational costs include Compute, Storage, and outbound Data Transfer.' },
  57: { ans: ['B', 'C'], cat: 'Billing & Support', exp: 'AWS Cost Management tools allow creating budgets with threshold alerts and breaking down spending by day, service, and linked account.' },
  58: { ans: ['C'], cat: 'Security & IAM', exp: 'Attaching an IAM Role to an Amazon EC2 instance provides secure temporary credentials without hardcoding secret access keys.' },
  59: { ans: ['B'], cat: 'Cloud Architecture', exp: 'Scaling horizontally across multiple Availability Zones provides high availability and fault resilience against single-instance failures.' },
  60: { ans: ['C'], cat: 'Cloud Foundations', exp: 'Agility is the speed and ease with which teams can innovate, build, test, and deploy software in the cloud.' },
  61: { ans: ['D'], cat: 'Cost & Optimization', exp: 'The "All Upfront" payment option for Reserved Instances offers the maximum percentage discount over on-demand rates.' },
  62: { ans: ['A', 'C'], cat: 'Cloud Architecture', exp: 'Distributing resources across multiple AZs and using Auto Scaling mitigates hardware failures and ensures continuous service availability.' },
  63: { ans: ['A', 'B'], cat: 'Cloud Foundations', exp: 'Managed services relieve internal IT teams of database software patching and physical storage capacity planning.' },
  64: { ans: ['A', 'C'], cat: 'Security & Compliance', exp: 'Core Trusted Advisor checks inspect S3 bucket open access permissions and verify root account Multi-Factor Authentication (MFA).' },
  65: { ans: ['D'], cat: 'Security & Compliance', exp: 'AWS manages the physical hardware, hypervisors, and global network infrastructure under the shared responsibility model.' },
  66: { ans: ['A', 'D'], cat: 'Cost & Optimization', exp: 'Using EC2 Auto Scaling to right-size capacity dynamically and purchasing Reserved Instances for steady workloads optimizes EC2 costs.' },
  67: { ans: ['A', 'E'], cat: 'Billing & Support', exp: 'Enterprise Support provides a dedicated TAM and a 15-minute response SLA for business-critical system outages.' },
  68: { ans: ['C'], cat: 'DevOps & Automation', exp: 'AWS Service Catalog allows organizations to create, govern, and distribute approved portfolios of IT services and templates.' },
  69: { ans: ['C'], cat: 'Security & Compliance', exp: 'On Amazon EC2 instances (IaaS), the customer is responsible for guest OS security patching and software updates.' },
  70: { ans: ['C', 'E'], cat: 'Cloud Architecture', exp: 'Decoupling monolithic architectures into modular components and engineering elasticity are core AWS cloud design principles.' },
  71: { ans: ['C', 'D'], cat: 'Security & Monitoring', exp: 'Amazon GuardDuty identifies unauthorized behaviors, compromised credentials, and anomalous API activity across AWS accounts.' },
  72: { ans: ['A'], cat: 'Security & Compliance', exp: 'Patching guest operating systems and application code on EC2 instances is strictly the customer responsibility.' },
  73: { ans: ['B'], cat: 'Cloud Architecture', exp: 'Designing an architecture across multiple AZs delivers high availability and guarantees workload continuity during disruptions.' },
  74: { ans: ['B', 'C'], cat: 'Cloud Foundations', exp: 'Benefits of AWS include rapid capacity elasticity and massive economies of scale passed down as lower pay-as-you-go pricing.' },
  75: { ans: ['C'], cat: 'Cloud Foundations', exp: 'AWS aggregates usage across hundreds of thousands of customers, creating massive economies of scale that reduce unit pricing.' },
  76: { ans: ['C'], cat: 'Compute', exp: 'AWS Step Functions, Amazon DynamoDB, and Amazon SNS are fully managed, serverless AWS services requiring no server provisioning.' },
  77: { ans: ['C'], cat: 'Security & Compliance', exp: 'On Amazon EC2, the customer is fully responsible for maintaining and patching the guest operating system.' },
  78: { ans: ['C'], cat: 'Security & Compliance', exp: 'Customers are responsible for enabling and managing data encryption at rest and in transit for their data.' },
  79: { ans: ['B'], cat: 'Cloud Foundations', exp: 'AWS enables pay-as-you-go agility with no upfront capital expenditure or long-term contract requirements.' },
  80: { ans: ['A'], cat: 'Cost & Optimization', exp: 'Standard Reserved Instances provide the highest discount (up to 72%) for predictable, 24/7 continuous steady-state database workloads.' },
  81: { ans: ['B', 'D'], cat: 'Security & Compliance', exp: 'AWS manages firmware upgrades on network devices and enforces physical security at data centers and edge locations.' },
  82: { ans: ['A', 'D'], cat: 'Networking', exp: 'Network ACLs are stateless subnet firewalls that process inbound and outbound rules sequentially starting with the lowest rule number.' },
  83: { ans: ['C'], cat: 'Cost & Optimization', exp: 'Designing systems to deliver business value at the lowest price point is the focus of the Cost Optimization pillar.' },
  84: { ans: ['B', 'E'], cat: 'Cloud Foundations', exp: 'Elasticity is the ability to acquire computing resources easily when needed and automatically right-size capacity as demand changes.' },
  85: { ans: ['A'], cat: 'Billing & Support', exp: 'Billing inquiries and questions about charges on AWS invoices can be submitted directly via a free billing case to AWS Support.' },
  86: { ans: ['A'], cat: 'Security & IAM', exp: 'Least privilege dictates granting users only the minimum permissions necessary to perform their required tasks.' },
  87: { ans: ['A', 'C'], cat: 'Security & Compliance', exp: 'Customers configure S3 bucket encryption settings and configure security group firewall rules.' },
  88: { ans: ['B'], cat: 'Billing & Support', exp: 'AWS Cost Explorer provides interactive visual graphs to review historical costs and forecast future AWS spending over time.' },
  89: { ans: ['B'], cat: 'Billing & Support', exp: 'AWS Enterprise Support includes a designated Technical Account Manager (TAM) and dedicated Concierge support team.' },
  90: { ans: ['A', 'C'], cat: 'Security & Compliance', exp: 'Customers are responsible for encrypting their data and ensuring their employees receive security and IAM awareness training.' },
  91: { ans: ['B'], cat: 'Security & Compliance', exp: 'AWS Artifact provides on-demand access to compliance certifications, SOC reports, and ISO documentation.' },
  92: { ans: ['A', 'C'], cat: 'Security & Monitoring', exp: 'AWS Config tracks asset inventory and changes, while AWS CloudTrail records all API activity into tamper-evident audit logs.' },
  93: { ans: ['B'], cat: 'Security & IAM', exp: 'An IAM Role can be attached to an Amazon EC2 instance to grant temporary AWS API credentials securely.' },
  94: { ans: ['B', 'D'], cat: 'Security & Compliance', exp: 'Clients are responsible for client-side data encryption and configuring Network ACL rules in their VPC.' },
  95: { ans: ['D'], cat: 'Cloud Architecture', exp: 'Loosely coupling components prevents failures in one service from bringing down other parts of the application.' },
  96: { ans: ['C', 'E'], cat: 'Databases', exp: 'Amazon RDS (Relational Database Service) and Amazon DynamoDB (NoSQL) are fully managed AWS database services.' },
  97: { ans: ['A', 'D'], cat: 'Networking', exp: 'Amazon Route 53 DNS routing and AWS Global Accelerator support multi-region traffic routing and instant automated failover.' },
  98: { ans: ['D'], cat: 'Security & Compliance', exp: 'AWS is responsible for maintaining and updating the virtualization hypervisors running in data center hardware.' },
  99: { ans: ['C'], cat: 'Security & Compliance', exp: 'AWS Artifact is the central compliance repository where customers can download AWS SOC 2, ISO, and PCI reports.' },
  100: { ans: ['B'], cat: 'Billing & Support', exp: 'Amazon Linux EC2 instances are billed per-second (with a 1-minute minimum), so running for 3 hours, 5 minutes, and 6 seconds is billed for that exact duration.' }
};
