// CCP 400 Answers & Explanations: Questions 101 - 200
module.exports = {
  101: { ans: ['A'], cat: 'Billing & Support', exp: 'When Free Tier limits or durations expire, AWS automatically bills standard pay-as-you-go service rates for subsequent usage without interruption.' },
  102: { ans: ['B'], cat: 'Security & Compliance', exp: 'Amazon Macie is a fully managed data security service that uses machine learning and pattern matching to discover and protect sensitive data (such as PII) in Amazon S3.' },
  103: { ans: ['C'], cat: 'Security & Compliance', exp: 'Under the Shared Responsibility Model, AWS is strictly responsible for the physical and environmental security of its data centers and global facilities.' },
  104: { ans: ['B', 'C'], cat: 'Cloud Foundations', exp: 'AWS Marketplace is a curated digital catalog enabling customers to buy third-party software that runs on AWS and allows ISVs to sell solutions to other AWS users.' },
  105: { ans: ['B', 'D'], cat: 'Networking', exp: 'AWS Edge Locations deliver cached static and dynamic content closer to end users via Amazon CloudFront, reducing load on backend origin servers.' },
  106: { ans: ['C'], cat: 'Cloud Architecture', exp: 'Amazon ECS (container orchestration) and Amazon DynamoDB (NoSQL database) seamlessly scale compute tasks and database read/write throughput on demand.' },
  107: { ans: ['C'], cat: 'Networking', exp: 'AWS Global Accelerator uses AWS global network infrastructure to optimize the path from users to applications, improving internet availability and performance by up to 60%.' },
  108: { ans: ['B', 'C'], cat: 'Security & Compliance', exp: 'Customers manage VPC network access control lists (NACLs) and are responsible for encrypting their data both in transit and at rest.' },
  109: { ans: ['A', 'D'], cat: 'Security & Compliance', exp: 'AWS is responsible for physical hardware security and maintaining the physical network and virtualization infrastructure.' },
  110: { ans: ['A'], cat: 'Cost & Optimization', exp: 'Physical security of data centers, power, cooling, and hardware maintenance are expenses eliminated when migrating from on-premises to AWS.' },
  111: { ans: ['C'], cat: 'Security & IAM', exp: 'AWS IAM Access Analyzer uses automated reasoning to evaluate resource-based policies and identify public or cross-account access to S3 buckets and IAM roles.' },
  112: { ans: ['C'], cat: 'Databases', exp: 'Amazon Aurora is an AWS cloud-native relational database engine that is fully compatible with MySQL and PostgreSQL.' },
  113: { ans: ['D'], cat: 'Compute', exp: 'AWS Snowball Edge devices include onboard compute capabilities that natively run Amazon EC2 compatible instances and AWS Lambda functions at edge locations.' },
  114: { ans: ['A', 'C'], cat: 'Security & Compliance', exp: 'Awareness & Training and Configuration Management are shared controls under the AWS Shared Responsibility Model.' },
  115: { ans: ['D'], cat: 'Cost & Optimization', exp: 'The Cost Optimization pillar advocates replacing upfront capacity guesswork with consumption-based pay-as-you-go provisioning.' },
  116: { ans: ['B'], cat: 'Databases', exp: 'Amazon RDS Multi-AZ deployments synchronously replicate database updates to a standby instance in a different AZ with automated failover in case of an outage.' },
  117: { ans: ['C', 'D'], cat: 'Cost & Optimization', exp: 'Comparing AWS vs on-premises TCO accounts for physical server hardware and dedicated SAN/NAS storage equipment capital expenditures.' },
  118: { ans: ['A', 'B'], cat: 'Billing & Support', exp: 'AWS Enterprise Support and Enterprise On-Ramp plans include consultative architecture guidance and support from Technical Account Managers.' },
  119: { ans: ['D'], cat: 'Billing & Support', exp: 'AWS Cost Explorer uses machine learning models to forecast estimated future AWS spending based on historical usage trends.' },
  120: { ans: ['B'], cat: 'Storage', exp: 'Amazon S3 Object Versioning preserves multiple variants of an object in the same bucket, allowing easy recovery from accidental overwrites or deletions.' },
  121: { ans: ['B', 'C'], cat: 'Databases', exp: 'When using DynamoDB, customers configure table encryption options and control access via IAM policies; AWS manages the underlying servers and OS.' },
  122: { ans: ['D'], cat: 'Cloud Architecture', exp: 'The Reliability pillar emphasizes architecting systems that automatically recover from component disruptions and service failures.' },
  123: { ans: ['B'], cat: 'Databases', exp: 'Amazon DynamoDB is a fully managed, serverless, key-value and document NoSQL database designed for single-digit millisecond performance.' },
  124: { ans: ['D'], cat: 'Cloud Architecture', exp: 'Amazon SQS (Simple Queue Service) provides fully managed message queuing to decouple and asynchronously coordinate distributed software components.' },
  125: { ans: ['B'], cat: 'Cloud Architecture', exp: 'To achieve high availability and fault tolerance, computing resources should be deployed across a minimum of two Availability Zones.' },
  126: { ans: ['B'], cat: 'Security & Compliance', exp: 'Updating firmware and maintaining server hardware across global facilities is AWS responsibility under Security OF the Cloud.' },
  127: { ans: ['A'], cat: 'Compute', exp: 'Launching EC2 instances across multiple Availability Zones in a single AWS Region guarantees high availability against single-AZ datacenter outages.' },
  128: { ans: ['D', 'E'], cat: 'Security & Compliance', exp: 'Customers are responsible for securing data in transit (TLS/SSL) and verifying data integrity at the application layer.' },
  129: { ans: ['B'], cat: 'Networking', exp: 'AWS Transit Gateway acts as a central cloud router connecting thousands of VPCs and on-premises networks across multiple regions in a hub-and-spoke topology.' },
  130: { ans: ['C'], cat: 'Security & Monitoring', exp: 'Amazon CloudWatch collects and monitors real-time operational metrics including CPU utilization, disk I/O, and network throughput for EC2 instances.' },
  131: { ans: ['A', 'E'], cat: 'DevOps & Automation', exp: 'Customers reduce OS patching overhead by adopting managed services (RDS, ECS, Lambda) and utilizing AWS Systems Manager Patch Manager.' },
  132: { ans: ['C'], cat: 'Cloud Architecture', exp: 'AWS Regions are geographically separated by hundreds of miles, ensuring that a natural or environmental disaster in one location does not impact other regions.' },
  133: { ans: ['D'], cat: 'Cloud Architecture', exp: 'Loose coupling reduces interdependencies between components, preventing failures in one service from cascading into dependent systems.' },
  134: { ans: ['C', 'D'], cat: 'Security & IAM', exp: 'Changing the AWS Support plan and creating Amazon CloudFront key pairs are privileged tasks requiring AWS account root user credentials.' },
  135: { ans: ['B'], cat: 'DevOps & Automation', exp: 'AWS CloudFormation provides Infrastructure as Code (IaC) by modeling and provisioning AWS resources using declarative JSON or YAML templates.' },
  136: { ans: ['A'], cat: 'Billing & Support', exp: 'AWS Organizations allows central governance, compliance enforcement via Service Control Policies (SCPs), and consolidated billing across multi-account structures.' },
  137: { ans: ['D'], cat: 'DevOps & Automation', exp: 'AWS Quick Starts are automated reference deployments built by AWS solutions architects using CloudFormation to quickly launch popular enterprise technologies.' },
  138: { ans: ['B'], cat: 'Networking', exp: 'Amazon CloudFront caches content at worldwide edge locations, delivering static and dynamic assets to global users with lowest latency.' },
  139: { ans: ['B', 'D'], cat: 'Cloud Foundations', exp: 'Key advantages of AWS include on-demand compute elasticity and enterprise-grade physical/network infrastructure security.' },
  140: { ans: ['A'], cat: 'Compute', exp: 'Amazon EC2 On-Demand Instances are ideal for short-term, unpredictable, spiky workloads without long-term commitment.' },
  141: { ans: ['B', 'C'], cat: 'Security & Compliance', exp: 'Patch Management and Cloud Awareness & Training are standard shared controls under the AWS Shared Responsibility Model.' },
  142: { ans: ['D'], cat: 'Security & Compliance', exp: 'Ensuring end-to-end encryption in transit (HTTPS/TLS) and at rest (SSE-S3 / SSE-KMS) protects sensitive data in Amazon S3.' },
  143: { ans: ['B'], cat: 'Cloud Architecture', exp: 'Deploying an Amazon RDS Multi-AZ database supports the Reliability pillar by providing automated failover and high availability.' },
  144: { ans: ['C'], cat: 'Billing & Support', exp: 'The AWS Pricing Calculator (and classic Simple Monthly Calculator) estimates monthly architecture costs prior to deployment.' },
  145: { ans: ['B'], cat: 'Security & Compliance', exp: 'Configuring firewalls (Security Groups and Network ACLs) and routing tables in a VPC is the customer responsibility.' },
  146: { ans: ['D'], cat: 'Compute', exp: 'When running Docker containers on Amazon EC2, the customer is responsible for patching and managing the EC2 host guest operating system.' },
  147: { ans: ['B', 'C'], cat: 'Cloud Foundations', exp: 'Cloud benefits include eliminating capacity guesswork through auto-scaling and increasing speed to market through on-demand provisioning.' },
  148: { ans: ['A', 'E'], cat: 'Security & Compliance', exp: 'Customer duties on EC2 include running antivirus/malware scans and configuring security groups and network ACLs.' },
  149: { ans: ['D'], cat: 'Compute', exp: 'AWS Outposts delivers native AWS infrastructure, services, and APIs directly to customer on-premises and edge locations for ultra-low latency processing.' },
  150: { ans: ['B'], cat: 'Cloud Foundations', exp: 'AWS Marketplace is the online software store for finding, testing, purchasing, and deploying verified third-party software and AMIs on AWS.' },
  151: { ans: ['C'], cat: 'Cloud Architecture', exp: 'The Reliability pillar encompasses the ability to prevent and quickly recover from failures to meet business and customer demand.' },
  152: { ans: ['C', 'D'], cat: 'Compute', exp: 'AWS Outposts and AWS Snowball Edge provide local AWS compute and storage hardware designed for on-premises and disconnected environments.' },
  153: { ans: ['B'], cat: 'Networking', exp: 'An Amazon VPC provides a logically isolated virtual network dedicated to a customer account within the AWS Cloud.' },
  154: { ans: ['A'], cat: 'Cloud Foundations', exp: 'AWS economies of scale allow passing operational efficiencies back to customers through continuous, systematic price reductions.' },
  155: { ans: ['C'], cat: 'Security & Monitoring', exp: 'Amazon GuardDuty is an intelligent threat detection service that continuously monitors AWS accounts, workloads, and data for malicious activity.' },
  156: { ans: ['B'], cat: 'Networking', exp: 'AWS Global Accelerator uses AWS global edge points of presence to route traffic through the congestion-free AWS private network backbone.' },
  157: { ans: ['B'], cat: 'Security & IAM', exp: 'An IAM User provides long-term credentials (Access Key ID and Secret Access Key) for programmatic CLI access.' },
  158: { ans: ['B'], cat: 'Security & Compliance', exp: 'AWS is solely responsible for physical security, environmental controls, and maintenance of global edge locations.' },
  159: { ans: ['B'], cat: 'Cloud Foundations', exp: 'AWS Regions are separate geographic areas around the globe containing multiple isolated Availability Zones.' },
  160: { ans: ['B'], cat: 'Cloud Architecture', exp: 'A core design principle for reliability is automatically recovering from failure using monitoring and automated healing mechanisms.' },
  161: { ans: ['A'], cat: 'Cloud Architecture', exp: 'Designing an application across multiple Availability Zones in a single AWS Region guarantees high availability against facility disruptions.' },
  162: { ans: ['D'], cat: 'Cloud Foundations', exp: 'Cloud agility means developers can provision compute, storage, and networking resources in minutes instead of weeks.' },
  163: { ans: ['A'], cat: 'Billing & Support', exp: 'Cost allocation tags enable organizing and tracking AWS costs on detailed billing reports by attaching metadata keys and values.' },
  164: { ans: ['C'], cat: 'Compute', exp: 'Amazon Elastic Container Service (Amazon ECS) is a highly scalable container orchestration service for running Docker containers on AWS.' },
  165: { ans: ['B'], cat: 'Compute', exp: 'AWS Elastic Beanstalk automatically provisions resources, load balances, and monitors the overall health of deployed web applications.' },
  166: { ans: ['A'], cat: 'Cloud Architecture', exp: 'The Reliability pillar design principle "Anticipate failure" guides architects to test disaster recovery strategies and simulate disruptions.' },
  167: { ans: ['C'], cat: 'Cost & Optimization', exp: 'When running on-premises, physical data center security and badge access controls contribute significantly to overall TCO.' },
  168: { ans: ['B'], cat: 'Security & IAM', exp: 'AWS IAM Access Analyzer analyzes resource policies to identify public access and provides recommendations to adhere to least privilege.' },
  169: { ans: ['C'], cat: 'Cloud Architecture', exp: 'Testing recovery procedures by creating simulated failures is a core Well-Architected design principle for Reliability.' },
  170: { ans: ['A'], cat: 'Cloud Foundations', exp: 'The AWS Service Health Dashboard displays the current operational status and historical uptime of all AWS services across all regions.' },
  171: { ans: ['B', 'E'], cat: 'Cloud Foundations', exp: 'Elasticity allows handling seasonal spikes by scaling resources on demand, while pay-as-you-go pricing ensures paying only for actual active usage.' },
  172: { ans: ['C', 'E'], cat: 'Cloud Architecture', exp: 'Testing recovery procedures and architecting systems to automatically recover from failure directly increase cloud reliability.' },
  173: { ans: ['A'], cat: 'Storage', exp: 'Amazon EFS (Elastic File System) and Amazon FSx provide managed, shared Network File System (NFS/SMB) file storage.' },
  174: { ans: ['D'], cat: 'Security & Compliance', exp: 'AWS Artifact provides on-demand access to AWS security reports (SOC 1/2/3, ISO 27001) and compliance agreements (BAA).' },
  175: { ans: ['A', 'B'], cat: 'Cloud Foundations', exp: 'AWS Trusted Advisor and AWS Professional Services assist organizations in reviewing architecture against best practices.' },
  176: { ans: ['A'], cat: 'Billing & Support', exp: 'AWS Organizations consolidated billing enables managing and controlling billing across multiple accounts from a single master account.' },
  177: { ans: ['B'], cat: 'Networking', exp: 'AWS Direct Connect establishes a dedicated, private physical network connection from an on-premises datacenter directly into AWS.' },
  178: { ans: ['B'], cat: 'Cloud Foundations', exp: 'Elasticity enables matching resource supply with real-time demand, eliminating wasteful underutilization of infrastructure.' },
  179: { ans: ['B'], cat: 'Databases', exp: 'In Amazon RDS, AWS manages the underlying operating system installation, patching, automated backups, and hardware maintenance.' },
  180: { ans: ['C'], cat: 'Security & IAM', exp: 'Service Control Policies (SCPs) define the maximum permission boundaries across accounts and organizational units (OUs) within AWS Organizations.' },
  181: { ans: ['D'], cat: 'Security & Compliance', exp: 'AWS Key Management Service (AWS KMS) enables creating and managing cryptographic keys used to encrypt data at rest across AWS services.' },
  182: { ans: ['C'], cat: 'Compute', exp: 'Amazon EC2 Spot Instances offer up to a 90% discount for fault-tolerant, interruptible data analysis and batch workloads.' },
  183: { ans: ['A', 'C'], cat: 'Billing & Support', exp: 'Consolidated billing in AWS Organizations aggregates usage across accounts to qualify for tier volume discounts and yields one unified monthly bill.' },
  184: { ans: ['C'], cat: 'Compute', exp: 'Amazon EC2 Dedicated Hosts give visibility and control over physical server cores, satisfying per-core/per-socket Bring Your Own License (BYOL) requirements.' },
  185: { ans: ['A'], cat: 'Networking', exp: 'Amazon CloudFront accelerates dynamic and static web delivery globally by caching responses at edge locations closest to end users.' },
  186: { ans: ['A', 'D'], cat: 'Billing & Support', exp: 'AWS Cost and Usage Reports provide granular cost records, while CloudWatch billing alarms alert when spending limits are approached.' },
  187: { ans: ['A'], cat: 'Storage', exp: 'Amazon Elastic File System (Amazon EFS) is a serverless, scalable file storage service for use with AWS Cloud services and on-premises resources.' },
  188: { ans: ['B'], cat: 'DevOps & Automation', exp: 'AWS CodeDeploy automates software deployments to a variety of compute services including Amazon EC2, Fargate, Lambda, and on-premises servers.' },
  189: { ans: ['B'], cat: 'Compute', exp: 'AWS Lambda runs code serverlessly on demand without managing or provisioning physical servers or virtual machine instances.' },
  190: { ans: ['B'], cat: 'Networking', exp: 'Elastic Load Balancing (ELB) automatically distributes incoming application traffic across multiple EC2 targets in multiple Availability Zones.' },
  191: { ans: ['D'], cat: 'Storage', exp: 'AWS Storage Gateway seamlessly connects on-premises software applications with AWS cloud storage (S3, EBS, Glacier).' },
  192: { ans: ['C'], cat: 'Billing & Support', exp: 'The AWS Simple Monthly Calculator (and modern AWS Pricing Calculator) models and anticipates future architecture expenses before deployment.' },
  193: { ans: ['D'], cat: 'Cloud Architecture', exp: 'Fault tolerance is the built-in ability of a system to continue operating without interruption even when one or more of its subcomponents fail.' },
  194: { ans: ['D'], cat: 'Databases', exp: 'Amazon Athena is an interactive, serverless query service that allows analyzing data directly in Amazon S3 using standard SQL.' },
  195: { ans: ['D'], cat: 'Cloud Foundations', exp: 'Agility refers to how quickly an organization can build, test, and launch new products and services using on-demand cloud resources.' },
  196: { ans: ['B', 'D'], cat: 'Cloud Foundations', exp: 'AWS benefits include on-demand compute elasticity and enterprise-grade infrastructure security.' },
  197: { ans: ['A'], cat: 'Compute', exp: 'Amazon Elastic Transcoder (and AWS Elemental MediaConvert) converts media files from source formats into versions optimized for playback on various devices.' },
  198: { ans: ['B'], cat: 'Billing & Support', exp: 'Consolidated billing in AWS Organizations allows rolling up costs from all departmental accounts into a single payment method.' },
  199: { ans: ['D'], cat: 'Cloud Foundations', exp: 'Pay-as-you-go pricing coupled with elasticity removes the need to guess infrastructure capacity before launching applications.' },
  200: { ans: ['A'], cat: 'Security & Monitoring', exp: 'AWS CloudTrail tracks and logs account actions, API calls, and console changes performed by users and services across the AWS account.' }
};
