// CCP 400 Answers & Explanations: Questions 301 - 400
module.exports = {
  301: { ans: ['A'], cat: 'Cost & Optimization', exp: 'AWS Compute Optimizer uses machine learning to analyze historical resource utilization metrics and recommend optimal rightsizing configurations.' },
  302: { ans: ['B', 'C'], cat: 'Cost & Optimization', exp: 'Consolidated billing in AWS Organizations aggregates multi-account usage to qualify for tiered volume pricing discounts and produces one combined monthly bill.' },
  303: { ans: ['B'], cat: 'Cost & Optimization', exp: 'Consolidated billing combines usage across all member accounts in an organization, maximizing volume pricing discounts on S3, EC2, and data transfer.' },
  304: { ans: ['A', 'C'], cat: 'Cloud Foundations', exp: 'Benefits of the AWS Cloud include trading upfront capital expenses for variable operational costs and deploying applications globally in minutes.' },
  305: { ans: ['D'], cat: 'Security & Compliance', exp: 'AWS is responsible for physical and environmental security, including fire suppression, HVAC, and physical access controls at data centers.' },
  306: { ans: ['C'], cat: 'Networking', exp: 'AWS Direct Connect establishes a dedicated, private physical fiber-optic connection bypassing the public internet between on-premises facilities and AWS.' },
  307: { ans: ['A', 'B'], cat: 'Security & Compliance', exp: 'AWS is responsible for managing the hypervisor layer and physical security of servers; customers manage OS patching and security groups.' },
  308: { ans: ['D'], cat: 'Cloud Architecture', exp: 'Loose coupling isolates components, so a failure or spike in one component does not break downstream application tiers.' },
  309: { ans: ['B'], cat: 'Cloud Architecture', exp: 'Horizontal scaling (scaling out) involves adding more instances to distribute load, rather than upgrading to a single larger instance (scaling up).' },
  310: { ans: ['C'], cat: 'Security & Compliance', exp: 'AWS Artifact provides self-service access to AWS compliance reports (SOC 1/2/3, PCI DSS, ISO certifications) and security agreements.' },
  311: { ans: ['A'], cat: 'Compute', exp: 'Amazon EC2 Spot Instances offer discounts up to 90% off On-Demand rates for fault-tolerant workloads with flexible start and end times.' },
  312: { ans: ['C'], cat: 'Storage', exp: 'Amazon S3 Standard provides 99.999999999% (11 9s) of data durability across multiple geographically separated Availability Zones.' },
  313: { ans: ['B', 'D'], cat: 'Compute', exp: 'AWS Lambda and AWS Fargate are serverless compute engines that execute code and containers without requiring customers to manage virtual servers.' },
  314: { ans: ['A'], cat: 'Networking', exp: 'Amazon Route 53 is a highly available and scalable cloud Domain Name System (DNS) web service.' },
  315: { ans: ['D'], cat: 'Cloud Foundations', exp: 'Deploying across multiple AWS Regions ensures low-latency access for international users and enhances disaster recovery posture.' },
  316: { ans: ['C'], cat: 'Cloud Architecture', exp: 'Decoupling components using messaging queues (Amazon SQS) ensures independent component resilience and prevents cascading failures.' },
  317: { ans: ['B'], cat: 'Security & Compliance', exp: 'Amazon Macie uses machine learning and pattern matching to discover, classify, and protect sensitive data (such as PII) stored in Amazon S3.' },
  318: { ans: ['A'], cat: 'Security & IAM', exp: 'Attaching an IAM Role to an Amazon EC2 instance grants secure, temporary credentials without storing long-term access keys on the instance.' },
  319: { ans: ['B', 'C'], cat: 'Cost & Optimization', exp: 'AWS Trusted Advisor support categories include Cost Optimization, Performance, Security, Fault Tolerance, and Service Quotas.' },
  320: { ans: ['C'], cat: 'Cloud Architecture', exp: 'Backup and restore is the simplest and least expensive disaster recovery strategy, storing backups in S3 and restoring resources only after a disaster occurs.' },
  321: { ans: ['B'], cat: 'Storage', exp: 'Amazon EC2 Instance Store provides temporary, ephemeral block-level storage located on disks physically attached to the host computer that is deleted upon stopping/terminating.' },
  322: { ans: ['C'], cat: 'Storage', exp: 'Amazon FSx for Windows File Server provides fully managed, highly reliable, and scalable file storage accessible via the industry-standard Server Message Block (SMB) protocol.' },
  323: { ans: ['B'], cat: 'Cloud Foundations', exp: 'AWS Regions, Availability Zones, and Edge Locations are the foundational physical components of the AWS Global Infrastructure.' },
  324: { ans: ['B'], cat: 'Networking', exp: 'An Internet Gateway is a horizontally scaled, redundant VPC component that enables bidirectional communication between instances in the VPC and the internet.' },
  325: { ans: ['C'], cat: 'Security & Compliance', exp: 'AWS Artifact is the central portal for downloading on-demand compliance reports, ISO certifications, and SOC assessments.' },
  326: { ans: ['D'], cat: 'Billing & Support', exp: 'The AWS Pricing Calculator allows estimating the cost of planned architectures before provisioning any resources in AWS.' },
  327: { ans: ['B'], cat: 'Compute', exp: 'Amazon EC2 Auto Scaling groups automatically replace unhealthy instances and add capacity across multiple Availability Zones to maintain high availability.' },
  328: { ans: ['B'], cat: 'Compute', exp: 'Amazon EC2 Spot Instances offer up to a 90% discount for stateless, fault-tolerant workloads that can tolerate interruptions.' },
  329: { ans: ['D', 'E'], cat: 'Security & IAM', exp: 'Enabling MFA for authentication and utilizing AWS Trusted Advisor security checks are recommended AWS security best practices.' },
  330: { ans: ['B'], cat: 'Billing & Support', exp: 'AWS Organizations allows consolidated billing, centralized policy management, and budget oversight across multiple AWS accounts.' },
  331: { ans: ['B'], cat: 'Security & Compliance', exp: 'Under the Shared Responsibility Model, the customer is responsible for configuring security groups and network access controls.' },
  332: { ans: ['B'], cat: 'Cloud Architecture', exp: 'High availability ensures an application remains accessible and operational even when underlying infrastructure components fail.' },
  333: { ans: ['B'], cat: 'Networking', exp: 'Subnets, Route Tables, Internet Gateways, NAT Gateways, and Network ACLs are foundational resources of an Amazon VPC.' },
  334: { ans: ['C', 'D'], cat: 'Cloud Foundations', exp: 'Elasticity allows dynamic scaling to match fluctuating demand, while pay-as-you-go pricing ensures paying only for actual resource usage.' },
  335: { ans: ['A'], cat: 'Storage', exp: 'AWS Snowball is a petabyte-scale data transport appliance designed to securely transfer massive volumes of data from on-premises to AWS.' },
  336: { ans: ['A'], cat: 'DevOps & Automation', exp: 'The AWS Command Line Interface (AWS CLI) is a unified tool to manage and script AWS services programmatically from the terminal.' },
  337: { ans: ['C'], cat: 'Compute', exp: 'AWS Outposts brings native AWS services, infrastructure, and operating models to virtually any on-premises datacenter or co-location space.' },
  338: { ans: ['B'], cat: 'Billing & Support', exp: 'The AWS Pricing Calculator creates cost estimates for proposed AWS resource configurations before committing funds.' },
  339: { ans: ['C'], cat: 'Cost & Optimization', exp: 'Amazon EC2 Reserved Instances provide significant discounts (up to 72%) for predictable, 24/7 steady-state database servers.' },
  340: { ans: ['A'], cat: 'Networking', exp: 'Amazon CloudFront caches photos and videos at global edge locations, delivering rich media content with low latency to international audiences.' },
  341: { ans: ['B'], cat: 'Billing & Support', exp: 'The AWS Knowledge Center contains answers to frequently asked questions and how-to guides written by AWS Support engineers.' },
  342: { ans: ['B', 'D'], cat: 'Networking', exp: 'AWS Direct Connect and AWS Storage Gateway extend on-premises networks and storage systems into the AWS Cloud.' },
  343: { ans: ['B'], cat: 'Billing & Support', exp: 'Amazon CloudWatch Billing Alarms monitor estimated AWS charges and trigger alerts when spending thresholds are reached.' },
  344: { ans: ['B'], cat: 'Security & Monitoring', exp: 'AWS CloudTrail logs all user sign-in events and API actions, providing detailed audit trails of user activity.' },
  345: { ans: ['C'], cat: 'DevOps & Automation', exp: 'AWS CodePipeline is a fully managed continuous delivery service that automates release pipelines for fast and reliable application updates.' },
  346: { ans: ['B'], cat: 'Databases', exp: 'Amazon Aurora is built with high availability by default, replicating 6 copies of data across 3 Availability Zones with self-healing storage.' },
  347: { ans: ['B'], cat: 'Storage', exp: 'AWS Storage Gateway connects on-premises environments seamlessly to cloud storage services like S3 and Glacier.' },
  348: { ans: ['C'], cat: 'Compute', exp: 'Amazon Comprehend is a natural language processing (NLP) service that uses machine learning to perform sentiment analysis on text and emails.' },
  349: { ans: ['D'], cat: 'Storage', exp: 'Amazon S3 provides virtually unlimited total storage capacity with individual object sizes supported up to 5 TB.' },
  350: { ans: ['C'], cat: 'Billing & Support', exp: 'The AWS Concierge Support team is a dedicated billing and account operational resource available exclusively to Enterprise Support customers.' },
  351: { ans: ['A'], cat: 'Security & Compliance', exp: 'AWS Artifact is the central compliance portal for downloading SOC reports, ISO certifications, and regulatory documentation.' },
  352: { ans: ['A'], cat: 'Compute', exp: 'AWS Elastic Beanstalk allows developers to upload application code while automatically handling capacity provisioning, load balancing, and auto-scaling.' },
  353: { ans: ['A', 'C'], cat: 'Security & Compliance', exp: 'Customer duties under the Shared Responsibility Model include managing IAM user permissions and applying OS patches on Amazon EC2 instances.' },
  354: { ans: ['A'], cat: 'Networking', exp: 'Amazon Route 53 DNS can route traffic to healthy endpoints and perform automatic DNS failover when health checks fail.' },
  355: { ans: ['A'], cat: 'Billing & Support', exp: 'AWS Budgets enables setting custom cost and usage limits, sending alerts via email or SNS when spending exceeds defined thresholds.' },
  356: { ans: ['C'], cat: 'Cost & Optimization', exp: 'All Upfront Reserved Instances provide the highest percentage discount over On-Demand rates for steady-state workloads.' },
  357: { ans: ['B'], cat: 'Compute', exp: 'Amazon EC2 Auto Scaling automatically adds or removes EC2 instances to dynamically match fluctuating demand.' },
  358: { ans: ['C'], cat: 'Cloud Foundations', exp: 'Elasticity allows automatically scaling computing resources up or down in real time to match changing business demands.' },
  359: { ans: ['B'], cat: 'Storage', exp: 'Amazon EBS (Elastic Block Store) provides persistent, high-performance block-level storage volumes for Amazon EC2 instances.' },
  360: { ans: ['A'], cat: 'Billing & Support', exp: 'Consolidated billing in AWS Organizations aggregates usage across all member accounts into a single monthly invoice.' },
  361: { ans: ['A'], cat: 'Security & Monitoring', exp: 'AWS CloudTrail captures all management console and API actions into audit logs, recording who made each request and when.' },
  362: { ans: ['B'], cat: 'Storage', exp: 'Amazon S3 Glacier Flexible Retrieval (and Deep Archive) offers low-cost, durable cold storage designed for compliance archiving.' },
  363: { ans: ['A', 'B'], cat: 'Security & Compliance', exp: 'Configuring IAM user permissions and patching guest operating systems on EC2 are customer responsibilities under the Shared Responsibility Model.' },
  364: { ans: ['A'], cat: 'Security & Compliance', exp: 'AWS Shield is a managed DDoS protection service safeguarding web applications on AWS from network and transport layer attacks.' },
  365: { ans: ['C'], cat: 'Security & Compliance', exp: 'AWS is responsible for physical and environmental security of the facilities housing AWS infrastructure.' },
  366: { ans: ['B', 'C'], cat: 'Cost & Optimization', exp: 'Consolidated billing combines usage across all linked accounts to share volume tier discounts and simplifies accounting with one bill.' },
  367: { ans: ['D'], cat: 'Cloud Architecture', exp: 'The Reliability pillar focuses on workloads performing correctly and consistently, with automated recovery from component disruptions.' },
  368: { ans: ['B'], cat: 'Compute', exp: 'Amazon EC2 Dedicated Hosts give physical server visibility and core socket control, satisfying per-socket and per-core software licensing requirements.' },
  369: { ans: ['D'], cat: 'Storage', exp: 'Amazon S3 provides highly durable (11 9s), virtually unlimited object storage for internet-accessible files and data lakes.' },
  370: { ans: ['A'], cat: 'Cloud Foundations', exp: 'Moving to AWS eliminates capital expenditures and recurring maintenance overhead associated with managing physical data center facilities.' },
  371: { ans: ['A', 'E'], cat: 'Storage', exp: 'Amazon S3 (with S3 File Gateway) and AWS Storage Gateway provide scalable file storage solutions accessible across networks.' },
  372: { ans: ['A'], cat: 'Networking', exp: 'Amazon CloudFront distributes video and streaming content with low latency using its worldwide network of edge location points of presence.' },
  373: { ans: ['D'], cat: 'Cloud Foundations', exp: 'AWS Global Infrastructure allows businesses to deploy applications worldwide in minutes to serve international customers with low latency.' },
  374: { ans: ['C'], cat: 'Billing & Support', exp: 'AWS Organizations enables consolidated billing to aggregate usage across accounts and achieve higher volume discount tiers.' },
  375: { ans: ['B'], cat: 'Security & IAM', exp: 'IAM Groups allow administrators to attach permission policies to a collection of users simultaneously, streamlining access management.' },
  376: { ans: ['A'], cat: 'Databases', exp: 'Amazon DynamoDB Global Tables provide fully managed, multi-region active-active database replication for globally distributed applications.' },
  377: { ans: ['B'], cat: 'Cloud Architecture', exp: 'Amazon SQS (Simple Queue Service) decouples application components, allowing microservices to communicate asynchronously.' },
  378: { ans: ['C'], cat: 'Cloud Architecture', exp: 'A hybrid cloud architecture connects on-premises legacy systems with cloud-hosted compute and storage resources.' },
  379: { ans: ['B'], cat: 'Cloud Architecture', exp: 'Anticipating failure and performing operations as code are foundational principles of the Operational Excellence pillar.' },
  380: { ans: ['B'], cat: 'Compute', exp: 'In Amazon WorkSpaces (virtual desktop service), the customer is responsible for managing, updating, and patching the Windows OS and user applications.' },
  381: { ans: ['D'], cat: 'Security & Monitoring', exp: 'AWS CloudTrail records API calls, detailing which identity stopped, terminated, or modified an EC2 instance.' },
  382: { ans: ['D'], cat: 'Storage', exp: 'Amazon S3 Glacier provides durable, secure, and cost-effective long-term data archiving suitable for multi-year regulatory retention.' },
  383: { ans: ['B'], cat: 'Cloud Architecture', exp: 'An AWS Well-Architected review evaluates architectures against cloud best practices to identify architectural gaps and improve efficiency.' },
  384: { ans: ['D'], cat: 'Cloud Architecture', exp: 'Combining EC2 Auto Scaling with an Application Load Balancer supports the Reliability pillar by ensuring automated elasticity and fault recovery.' },
  385: { ans: ['C'], cat: 'Security & Compliance', exp: 'Under the Shared Responsibility Model, AWS is responsible for updating firmware and hardware drivers on physical underlying EC2 hosts.' },
  386: { ans: ['A'], cat: 'DevOps & Automation', exp: 'AWS CloudFormation allows modeling and provisioning infrastructure resources systematically using Infrastructure as Code (IaC).' },
  387: { ans: ['D'], cat: 'Cloud Architecture', exp: 'High availability is the ability of an architecture to withstand component failures without experiencing service downtime.' },
  388: { ans: ['A'], cat: 'Compute', exp: 'When using AWS Lambda, creating function versions and aliases and managing code releases are customer responsibilities.' },
  389: { ans: ['D'], cat: 'Billing & Support', exp: 'AWS Cost and Usage Reports (CUR) provide comprehensive, granular breakdown of AWS costs and resource usage metadata.' },
  390: { ans: ['A', 'E'], cat: 'Security & IAM', exp: 'To grant console access with least privilege, create an IAM user with Management Console access and attach a scoped IAM policy for Amazon RDS.' },
  391: { ans: ['C'], cat: 'Cloud Architecture', exp: 'Designing for automated recovery from failure using health checks and auto scaling is a core Well-Architected principle for Reliability.' },
  392: { ans: ['D'], cat: 'DevOps & Automation', exp: 'AWS X-Ray traces and analyzes requests flowing through serverless microservices including API Gateway, Lambda, and DynamoDB.' },
  393: { ans: ['C'], cat: 'Databases', exp: 'Amazon Redshift is a fast, scalable, fully managed petabyte-scale data warehouse designed for complex analytical SQL queries.' },
  394: { ans: ['B', 'D'], cat: 'Cloud Foundations', exp: 'Immediate benefits include trading upfront capital expenses for variable operational costs and gaining rapid business agility.' },
  395: { ans: ['A', 'C'], cat: 'Cost & Optimization', exp: 'Economic benefits of AWS include lowering Total Cost of Ownership (TCO) and reducing operational expenditures through managed efficiencies.' },
  396: { ans: ['B'], cat: 'Security & IAM', exp: 'AWS Identity and Access Management (IAM) is a core security feature provided at no additional charge for all AWS accounts.' },
  397: { ans: ['A', 'D'], cat: 'Security & IAM', exp: 'Best practices for IAM include configuring strong password policies and rotating access keys regularly.' },
  398: { ans: ['C'], cat: 'DevOps & Automation', exp: 'AWS CloudFormation provides declarative JSON/YAML templates that can be reused to deploy consistent infrastructure stacks across environments.' },
  399: { ans: ['A'], cat: 'Cost & Optimization', exp: 'AWS lowers TCO by replacing large upfront capital expenditures (capex) with flexible, pay-as-you-go variable operational expenses.' },
  400: { ans: ['B'], cat: 'Networking', exp: 'Amazon CloudFront delivers web content with low latency to a global audience using its worldwide network of edge location caching servers.' }
};
