// CCP 400 Answers & Explanations: Questions 201 - 300
module.exports = {
  201: { ans: ['B', 'C'], cat: 'Security & Compliance', exp: 'Customers are responsible for installing OS security patches on EC2 Linux instances and choosing encryption settings for data stored in Amazon S3.' },
  202: { ans: ['C'], cat: 'Security & IAM', exp: 'An IAM account password policy sets requirements (minimum length, character complexity, expiration) for IAM users signing into the AWS Management Console.' },
  203: { ans: ['A'], cat: 'Security & Monitoring', exp: 'AWS Trusted Advisor includes security checks that identify security groups allowing unrestricted access (0.0.0.0/0) to specific ports.' },
  204: { ans: ['C'], cat: 'Security & Compliance', exp: 'AWS KMS (Key Management Service) lets users create, rotate, and manage cryptographic keys to encrypt and decrypt data across AWS workloads.' },
  205: { ans: ['D'], cat: 'DevOps & Automation', exp: 'AWS Systems Manager Patch Manager automates the scheduled rollout of operating system and database security patches across EC2 instance fleets.' },
  206: { ans: ['B'], cat: 'Compute', exp: 'Amazon EC2 Auto Scaling automatically increases or decreases the number of EC2 instances based on demand to maintain performance and optimize costs.' },
  207: { ans: ['D'], cat: 'Security & IAM', exp: 'The principle of least privilege means granting an entity only the minimum permissions necessary to perform its intended job function.' },
  208: { ans: ['B'], cat: 'Cloud Architecture', exp: 'Deploying an Amazon RDS instance across multiple Availability Zones (Multi-AZ) embodies the "Design for failure" principle with automated standby failover.' },
  209: { ans: ['D'], cat: 'Security & Compliance', exp: 'When running applications on Amazon EC2 (IaaS), the customer is responsible for managing application software updates and security dependencies.' },
  210: { ans: ['C'], cat: 'Cloud Foundations', exp: 'Every AWS Region is a physical geographical location that consists of multiple, isolated, and physically separated Availability Zones (AZs).' },
  211: { ans: ['C'], cat: 'Networking', exp: 'AWS Direct Connect creates a dedicated, private physical network connection between an on-premises network and AWS without traversing the public internet.' },
  212: { ans: ['C'], cat: 'Security & IAM', exp: 'AWS IAM policies define fine-grained JSON permissions to grant or restrict user access to specific Amazon S3 buckets and resources.' },
  213: { ans: ['C'], cat: 'Cloud Architecture', exp: 'Learning from operational failures and conducting root-cause post-mortems is a core design principle of the Operational Excellence pillar.' },
  214: { ans: ['C'], cat: 'Networking', exp: 'Amazon Route 53 is a highly available and scalable DNS web service that can route end users to internet applications and perform health check failovers.' },
  215: { ans: ['A'], cat: 'Billing & Support', exp: 'The Developer Support plan provides one-on-one business-hours email access to Cloud Support Associates via support cases in the AWS Support Center.' },
  216: { ans: ['D'], cat: 'DevOps & Automation', exp: 'AWS X-Ray helps developers analyze and debug distributed applications, such as those built using a microservices architecture.' },
  217: { ans: ['C', 'E'], cat: 'Security & Compliance', exp: 'Customers are responsible for the configuration management of their applications and configuring security group firewall rules.' },
  218: { ans: ['B'], cat: 'Cost & Optimization', exp: 'AWS Trusted Advisor inspects your AWS environment and provides actionable recommendations to optimize performance, security, and cost.' },
  219: { ans: ['D', 'E'], cat: 'Cost & Optimization', exp: 'AWS charges primarily for active compute resources in use and outbound data transfer across the internet.' },
  220: { ans: ['A'], cat: 'Security & Monitoring', exp: 'AWS Config continually records, evaluates, and audits configuration changes of AWS resources to satisfy compliance and governance mandates.' },
  221: { ans: ['B'], cat: 'Storage', exp: 'Amazon S3 Glacier is an extremely low-cost, secure, and durable storage class designed specifically for long-term data archiving and backups.' },
  222: { ans: ['A', 'B'], cat: 'Cloud Foundations', exp: 'The cloud delivers rapid execution speed and business agility through on-demand resource provisioning in minutes and scalable compute capacity.' },
  223: { ans: ['C'], cat: 'Cloud Architecture', exp: 'Scalability is the ability of a system to increase or decrease computing capacity in accordance with current workload demands.' },
  224: { ans: ['C'], cat: 'Storage', exp: 'Amazon S3 Intelligent-Tiering automatically moves objects between frequent, infrequent, and archive access tiers based on changing access patterns with no operational overhead.' },
  225: { ans: ['B', 'D'], cat: 'Networking', exp: 'Establishing an AWS Site-to-Site VPN or AWS Direct Connect dedicated link allows secure hybrid communication between on-premises and AWS VPC resources.' },
  226: { ans: ['D'], cat: 'Networking', exp: 'AWS Transit Gateway simplifies network architecture by acting as a centralized hub connecting multiple VPCs and on-premises networks.' },
  227: { ans: ['B'], cat: 'Cloud Foundations', exp: 'Operating across multiple global Regions provides worldwide infrastructure to reach users globally with low latency.' },
  228: { ans: ['B'], cat: 'DevOps & Automation', exp: 'AWS OpsWorks is a configuration management service that provides managed instances of Chef and Puppet to automate server configuration.' },
  229: { ans: ['D'], cat: 'Cloud Foundations', exp: 'Pay-as-you-go pricing allows organizations to scale up or down without needing to predict capacity requirements in advance.' },
  230: { ans: ['A'], cat: 'Security & Compliance', exp: 'AWS WAF (Web Application Firewall) protects web applications from common web exploits like SQL injection and cross-site scripting (XSS).' },
  231: { ans: ['D'], cat: 'Compute', exp: 'Amazon EC2 Auto Scaling dynamically adjusts the number of EC2 instances to maintain performance and ensure elasticity.' },
  232: { ans: ['B'], cat: 'Compute', exp: 'Amazon Rekognition uses deep learning to automatically detect objects, scenes, text, and faces in images and video streams.' },
  233: { ans: ['A'], cat: 'Storage', exp: 'AWS Snowball is a secure edge storage and compute device designed to physically transfer petabytes of data into AWS.' },
  234: { ans: ['A'], cat: 'Cloud Foundations', exp: 'AWS Marketplace is a digital catalog where customers can discover, test, purchase, and deploy third-party software that runs on AWS.' },
  235: { ans: ['B'], cat: 'Cloud Architecture', exp: 'A Multi-Region active-active architecture serves traffic from multiple regions concurrently, providing maximum availability and lowest latency worldwide.' },
  236: { ans: ['D'], cat: 'Security & Compliance', exp: 'When running Amazon EC2 instances, the customer is fully responsible for maintaining and updating the guest operating system.' },
  237: { ans: ['C'], cat: 'Cloud Architecture', exp: 'Deploying applications across multiple geographically distinct AWS Regions protects workloads from wide-scale regional natural disasters or disruptions.' },
  238: { ans: ['B'], cat: 'Cloud Architecture', exp: 'A serverless architecture combining static S3 hosting, event-driven AWS Lambda compute, and Amazon DynamoDB is decoupled, scalable, and highly available.' },
  239: { ans: ['C'], cat: 'Billing & Support', exp: 'Using Consolidated Billing in AWS Organizations combines all linked accounts into a single bill and shares volume discounts.' },
  240: { ans: ['D'], cat: 'Cloud Foundations', exp: 'AWS global footprint enables deploying applications and data in multiple regions close to international end users.' },
  241: { ans: ['B'], cat: 'Security & Compliance', exp: 'Under the Shared Responsibility Model, AWS is solely responsible for physical facilities, data center hardware, and the virtualization hypervisor layer.' },
  242: { ans: ['B'], cat: 'Security & IAM', exp: 'When AWS-managed policies do not match exact business requirements, administrators create customer-managed IAM policies.' },
  243: { ans: ['B'], cat: 'Security & IAM', exp: 'AWS Systems Manager Session Manager provides secure, auditable instance management via the console or CLI without opening inbound SSH ports or managing bastion hosts.' },
  244: { ans: ['D'], cat: 'Compute', exp: 'Amazon EC2 Spot Instances offer steep discounts (up to 90%) for stateless, fault-tolerant, and interruptible workloads.' },
  245: { ans: ['D'], cat: 'Networking', exp: 'Amazon SNS (Simple Notification Service) is a fully managed pub/sub messaging service capable of sending high-throughput messages and push notifications to subscribers.' },
  246: { ans: ['A', 'E'], cat: 'Security & IAM', exp: 'Changing an AWS Support plan and closing an AWS account require authenticating as the AWS account root user.' },
  247: { ans: ['B'], cat: 'Cloud Architecture', exp: 'Dynamically and predictively scaling compute resources in response to real-time demand leverages cloud elasticity.' },
  248: { ans: ['B'], cat: 'Networking', exp: 'Amazon Route 53 is a scalable Domain Name System (DNS) web service that allows users to register domain names and manage DNS records.' },
  249: { ans: ['C'], cat: 'Networking', exp: 'VPC Peering allows connecting two VPCs directly using private IPv4/IPv6 addresses as if they were in the same network.' },
  250: { ans: ['B'], cat: 'Security & IAM', exp: 'IAM Roles provide secure, temporary credentials to EC2 instances and AWS services without requiring long-term access keys.' },
  251: { ans: ['A'], cat: 'Cloud Foundations', exp: 'AWS global infrastructure allows organizations to deploy applications globally in multiple regions within minutes.' },
  252: { ans: ['C'], cat: 'Databases', exp: 'Amazon DynamoDB is a fast and flexible NoSQL database service that provides consistent, single-digit millisecond latency at any scale.' },
  253: { ans: ['C'], cat: 'Billing & Support', exp: 'AWS Partner Network (APN) Consulting Partners are professional services firms that help customers design, build, and migrate workloads to AWS.' },
  254: { ans: ['C'], cat: 'Security & Compliance', exp: 'AWS Control Tower provides the easiest way to set up and govern a secure, multi-account AWS environment based on best practices.' },
  255: { ans: ['A'], cat: 'Security & IAM', exp: 'Closing an AWS account is a root user action that cannot be delegated to an IAM user or role.' },
  256: { ans: ['C'], cat: 'Compute', exp: 'AWS Fargate is a serverless compute engine for Amazon ECS and EKS that eliminates the need to provision or manage EC2 servers for containers.' },
  257: { ans: ['A', 'B'], cat: 'Cloud Foundations', exp: 'Scaling EC2 instances with auto scaling and resizing RDS instances as demand shifts are direct examples of cloud elasticity.' },
  258: { ans: ['A', 'C'], cat: 'Cloud Foundations', exp: 'AWS requires no upfront financial commitments and allows users to provision resources on demand with self-service APIs.' },
  259: { ans: ['A', 'C'], cat: 'Cloud Foundations', exp: 'AWS handles the physical maintenance of data center infrastructure and capacity planning for physical hardware hosts.' },
  260: { ans: ['D'], cat: 'DevOps & Automation', exp: 'AWS CloudFormation provides Infrastructure as Code (IaC), allowing infrastructure to be defined, versioned, and deployed via code templates.' },
  261: { ans: ['A', 'C'], cat: 'Security & Compliance', exp: 'Customers are responsible for updating guest OS on EC2 instances and managing data lifecycle policies in Amazon S3.' },
  262: { ans: ['A'], cat: 'Billing & Support', exp: 'AWS Organizations allows central administration and consolidated billing across all linked departmental accounts.' },
  263: { ans: ['A'], cat: 'Networking', exp: 'Elastic Load Balancing automatically distributes incoming application traffic across multiple targets (such as EC2 instances) in multiple AZs.' },
  264: { ans: ['C'], cat: 'Cloud Architecture', exp: 'Decoupling application components ensures that failures in one component do not trigger cascading failures in upstream or downstream services.' },
  265: { ans: ['C'], cat: 'Security & Compliance', exp: 'Physical security of AWS data centers is strictly the responsibility of AWS under the Shared Responsibility Model.' },
  266: { ans: ['A', 'B'], cat: 'Security & Compliance', exp: 'Security IN the Cloud (customer responsibility) includes IAM user access controls and guest operating system security updates.' },
  267: { ans: ['C'], cat: 'Storage', exp: 'Amazon S3 Standard provides 99.999999999% (11 9s) of data durability across multiple Availability Zones.' },
  268: { ans: ['B'], cat: 'Security & IAM', exp: 'IAM groups allow administrators to assign access permissions to multiple users collectively, simplifying permission management.' },
  269: { ans: ['C'], cat: 'Networking', exp: 'VPC Peering allows connecting two VPCs using private IP addresses without routing traffic across the public internet.' },
  270: { ans: ['A'], cat: 'Compute', exp: 'Amazon Polly is a machine learning service that turns text into lifelike speech in dozens of languages and voices.' },
  271: { ans: ['C'], cat: 'Cost & Optimization', exp: 'Amazon EC2 Spot Instances utilize unused EC2 spare capacity with pricing dynamically adjusted based on supply and demand.' },
  272: { ans: ['B'], cat: 'Billing & Support', exp: 'AWS Organizations helps centrally govern, manage, and consolidate billing for multiple AWS accounts.' },
  273: { ans: ['A'], cat: 'Networking', exp: 'VPC Flow Logs capture detailed information about IP traffic going to and from network interfaces in a VPC.' },
  274: { ans: ['C'], cat: 'Billing & Support', exp: 'AWS Support provides live chat, phone, and web case contact channels depending on the support tier.' },
  275: { ans: ['A'], cat: 'Billing & Support', exp: 'AWS Budgets enables tracking custom cost and usage thresholds, with alerts sent via email or SNS when limits are exceeded.' },
  276: { ans: ['C', 'E'], cat: 'Security & Compliance', exp: 'In managed database services (e.g. RDS), AWS automates database backups and installs underlying operating system patches.' },
  277: { ans: ['A', 'C', 'D'], cat: 'Billing & Support', exp: 'The AWS Pricing Calculator, Simple Monthly Calculator, and TCO Calculator help estimate and model cloud deployment costs.' },
  278: { ans: ['B'], cat: 'Cloud Architecture', exp: 'Placing EC2 instances in two separate Availability Zones within the same Region ensures they are in physically distinct, redundant data centers.' },
  279: { ans: ['D'], cat: 'Cost & Optimization', exp: 'AWS replaces heavy upfront capital expenses with lower variable pay-as-you-go operational costs.' },
  280: { ans: ['B'], cat: 'Security & Compliance', exp: 'The AWS Abuse team handles reports of abusive behavior, spam, DDoS, or intrusion attempts originating from AWS IP addresses.' },
  281: { ans: ['B'], cat: 'Cloud Architecture', exp: 'Deploying across multiple Availability Zones provides high availability with automatic failover in case of a facility outage.' },
  282: { ans: ['B', 'D'], cat: 'Security & IAM', exp: 'IAM users are created for individual human identities needing credentials or to be organized into IAM groups.' },
  283: { ans: ['A'], cat: 'Security & IAM', exp: 'Attaching an IAM policy to an IAM group applies identical permissions to all member users simultaneously.' },
  284: { ans: ['C'], cat: 'Security & Compliance', exp: 'AWS KMS (Key Management Service) integrates seamlessly with Amazon EBS to encrypt block storage volumes and snapshots.' },
  285: { ans: ['D'], cat: 'Billing & Support', exp: 'APN Technology Partners provide software solutions that are hosted on or integrated with the AWS Cloud platform.' },
  286: { ans: ['A', 'C'], cat: 'DevOps & Automation', exp: 'AWS Elastic Beanstalk and AWS OpsWorks automate application deployment and configuration management.' },
  287: { ans: ['B', 'C'], cat: 'Networking', exp: 'Amazon CloudFront and AWS Global Accelerator utilize global edge locations to optimize content delivery and routing.' },
  288: { ans: ['B', 'C'], cat: 'Security & Compliance', exp: 'On EC2 instances, customers are responsible for guest OS firewall configuration and file-system-level encryption.' },
  289: { ans: ['A'], cat: 'Compute', exp: 'AWS IoT Greengrass extends AWS cloud capabilities to local edge devices so they can act locally on generated data.' },
  290: { ans: ['C'], cat: 'Databases', exp: 'Amazon Neptune is a fast, reliable, fully managed graph database service optimized for highly connected datasets like social networks.' },
  291: { ans: ['B'], cat: 'Databases', exp: 'Amazon DynamoDB is a fully managed NoSQL key-value and document database service.' },
  292: { ans: ['B'], cat: 'Security & Networking', exp: 'Security Groups act as a stateful virtual firewall at the instance level to control inbound and outbound traffic.' },
  293: { ans: ['D'], cat: 'Billing & Support', exp: 'Cost allocation tags allow categorizing and tracking AWS costs across multiple applications running within the same account.' },
  294: { ans: ['C'], cat: 'Compute', exp: 'Distributing batch workloads across multiple EC2 instances to run in parallel reduces total processing time significantly.' },
  295: { ans: ['A'], cat: 'Cost & Optimization', exp: 'All Upfront Standard Reserved Instances yield the largest possible discount for 1-year steady-state continuous workloads.' },
  296: { ans: ['B', 'C'], cat: 'Cost & Optimization', exp: 'AWS Trusted Advisor provides cost optimization recommendations and detects security permission vulnerabilities.' },
  297: { ans: ['A'], cat: 'Security & Monitoring', exp: 'Amazon CloudWatch monitors performance metrics like CPU utilization, memory, and disk I/O across EC2 instances.' },
  298: { ans: ['D'], cat: 'Billing & Support', exp: 'AWS Organizations consolidated billing provides aggregated billing through a master payer management account.' },
  299: { ans: ['B'], cat: 'Cloud Foundations', exp: 'Migrating to AWS provides on-demand access to modern IT resources, eliminating lengthy multi-year hardware refresh cycles.' },
  300: { ans: ['A'], cat: 'Security & Compliance', exp: 'AWS Shield is a managed Distributed Denial of Service (DDoS) protection service that safeguards applications running on AWS.' }
};
